### PR TITLE
Applying same order as in request when sending a batch request

### PR DESCRIPTION
**Pull request by kraglik**
(Some jsonrpc server implementations don't sort batch responses)

### CODE REVIEW

**Comment by bcb** [comment]
The spec mentions:

> The Response objects being returned from a batch call MAY be returned in any order within the Array. The Client SHOULD match contexts between the set of Request objects and the resulting set of Response objects based on the id member within each Object.

Although sorting is reasonably harmless, there is a performance hit. Is it just a nice to have?

**Comment by kraglik** [comment]
Yep, is's just nice to have. But, there are cases when response should be sorted, so let's make it optional.

**Comment by bcb** [comment]
Can you give an example where its needed, because it might be better as a function added to your own project.

Can I suggest a `by_id` function instead, which gets a response by its id — this would be closer to the spec.

**Comment by bcb** [comment]
If you want this I’d prefer a separate function, for example
```python
sort _batch(request, response.data)
```
Rather than adding to `send`.

**Pull request closed without merging**
